# Generated by Django 5.1.4 on 2024-12-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossier_patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id_medicament', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('forme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Administratif',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            options={
                'verbose_name': 'Administratif',
                'verbose_name_plural': 'Administratifs',
            },
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Laborantin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('specialite', models.CharField(default='generaliste', max_length=50)),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Radiologue',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='SGPH',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ordonnance', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('dpi_patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='dossier_patient.dossiermedical')),
                ('medecin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id_traitement', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('description', models.CharField(default='Après repas', max_length=500)),
                ('duree', models.CharField(max_length=100)),
                ('medicament', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.medicament')),
                ('ordonnance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='utilisateurs.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id_resume', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('antecedents', models.TextField()),
                ('observations', models.TextField()),
                ('diagnostic', models.TextField()),
                ('dpi', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='dossier_patient.dossiermedical')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='utilisateurs.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id_bilan', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('glycimie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cholesteroel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pression_arterielle', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dpi', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='dossier_patient.dossiermedical')),
                ('laborantin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans', to='utilisateurs.laborantin')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans', to='utilisateurs.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('nss', models.CharField(max_length=50, unique=True)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField(default='Adresse inconnue')),
                ('telephone', models.CharField(default='0000000000', max_length=15)),
                ('mutuelle', models.CharField(blank=True, max_length=50, null=True)),
                ('personne', models.TextField(default='numero inconnue')),
                ('medecin_traitant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.medecin')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='RapportImagerie',
            fields=[
                ('id_rapport', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('radiologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.radiologue')),
            ],
        ),
    ]
