# Generated by Django 5.1.4 on 2024-12-12 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RapportImagerie',
            fields=[
                ('id_rapport', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Administratif',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            options={
                'verbose_name': 'Administratif',
                'verbose_name_plural': 'Administratifs',
            },
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Laborantin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Radiologue',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='SGPH',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id_soin', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.infirmier')),
            ],
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id_bilan', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('laborantin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.laborantin')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id_resume', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_resume', models.DateField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ordonnance', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('infirmiers', models.ManyToManyField(to='utilisateurs.infirmier')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('nss', models.CharField(max_length=50, unique=True)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('medecin_traitant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.medecin')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id_dpi', models.AutoField(primary_key=True, serialize=False)),
                ('bilans', models.ManyToManyField(blank=True, to='utilisateurs.bilanbiologique')),
                ('ordonnances', models.ManyToManyField(blank=True, to='utilisateurs.ordonnance')),
                ('images', models.ManyToManyField(blank=True, to='utilisateurs.rapportimagerie')),
                ('consultations', models.ManyToManyField(blank=True, to='utilisateurs.resume')),
                ('soins', models.ManyToManyField(blank=True, to='utilisateurs.soin')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.patient')),
            ],
        ),
        migrations.AddField(
            model_name='rapportimagerie',
            name='radiologue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.radiologue'),
        ),
    ]
