# Generated by Django 5.1.4 on 2024-12-21 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_remove_patient_email_utilisateur_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('forme', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('duree', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='ordonnances',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='infirmiers',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='medicaments',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.patient'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='medecin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.medecin'),
        ),
    ]
