# Generated by Django 5.1.4 on 2024-12-21 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_medicament_remove_dpi_ordonnances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='medicaments',
        ),
        migrations.AddField(
            model_name='medicament',
            name='ordonnance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='utilisateurs.ordonnance'),
        ),
    ]
