# Generated by Django 5.1.4 on 2024-12-21 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_remove_ordonnance_medicaments_medicament_ordonnance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='patient',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='dpi_patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='utilisateurs.dpi'),
        ),
    ]
