# Generated by Django 5.1.4 on 2024-12-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_remove_ordonnance_patient_ordonnance_dpi_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medecin_traitant',
        ),
        migrations.AddField(
            model_name='patient',
            name='mutuelle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.TextField(default='Adresse inconnue'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('patient', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='utilisateurs.patient')),
            ],
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='dpi_patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='utilisateurs.dossiermedical'),
        ),
        migrations.DeleteModel(
            name='DPI',
        ),
    ]
