# Generated by Django 5.1.4 on 2024-12-23 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_remove_patient_medecin_traitant_patient_mutuelle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='date_resume',
            new_name='date',
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='dpi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='utilisateurs.dossiermedical'),
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='result',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='dpi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='utilisateurs.dossiermedical'),
        ),
        migrations.AlterField(
            model_name='bilanbiologique',
            name='laborantin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans', to='utilisateurs.laborantin'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='utilisateurs.medecin'),
        ),
    ]
