# Generated by Django 5.1.4 on 2024-12-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_rename_date_resume_resume_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(default='generaliste', max_length=50),
        ),
    ]
