# Generated by Django 5.1.4 on 2024-12-23 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_medecin_specialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='ordonnance',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='quantite',
        ),
        migrations.AddField(
            model_name='medicament',
            name='id_medicament',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id_traitement', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('description', models.CharField(default='Après repas', max_length=500)),
                ('duree', models.CharField(max_length=100)),
                ('medicament', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.medicament')),
                ('ordonnance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='utilisateurs.ordonnance')),
            ],
        ),
    ]
