# Generated by Django 5.1.4 on 2024-12-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_patient', '0007_alter_dossiermedical_patient_delete_patient'),
        ('utilisateurs', '0009_remove_medicament_duree_remove_medicament_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='dpi_patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='dossier_patient.dossiermedical'),
        ),
        migrations.AlterField(
            model_name='bilanbiologique',
            name='dpi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='dossier_patient.dossiermedical'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='dpi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='dossier_patient.dossiermedical'),
        ),
        migrations.RemoveField(
            model_name='soin',
            name='infirmier',
        ),
        migrations.AddField(
            model_name='patient',
            name='medecin_traitant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.medecin'),
        ),
        migrations.AddField(
            model_name='patient',
            name='personne',
            field=models.TextField(default='numero inconnue'),
        ),
        migrations.DeleteModel(
            name='DossierMedical',
        ),
        migrations.DeleteModel(
            name='Soin',
        ),
    ]
