# Generated by Django 5.1.4 on 2024-12-25 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_alter_ordonnance_dpi_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbiologique',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans', to='utilisateurs.medecin'),
        ),
    ]
