# Generated by Django 5.1.4 on 2024-12-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.CharField(max_length=15, null=True, unique=True)),
                ('nom', models.CharField(default='Nom inconnu', max_length=50)),
                ('prenom', models.CharField(default='Prénom inconnu', max_length=50)),
                ('date_naissance', models.DateField(default='2000-01-01')),
                ('adresse', models.TextField(default='Adresse inconnue')),
                ('telephone', models.CharField(default='0000000000', max_length=15)),
                ('mutuelle', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
    ]
