# Generated by Django 5.1.4 on 2024-12-20 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.CharField(max_length=15, null=True, unique=True)),
                ('nom', models.CharField(default='Nom inconnu', max_length=50)),
                ('prenom', models.CharField(default='Prénom inconnu', max_length=50)),
                ('date_naissance', models.DateField(default='2000-01-01')),
                ('adresse', models.TextField(default='Adresse inconnue')),
                ('telephone', models.CharField(default='0000000000', max_length=15)),
                ('mutuelle', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='mutuelle',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='nss',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='telephone',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='dossier_patient.patient'),
        ),
    ]
