# Generated by Django 5.1.4 on 2024-12-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossier_patient', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compterendu',
            name='radiologue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compte_rendus', to='utilisateurs.radiologue'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='utilisateurs.patient'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='dossier_medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compte_rendus', to='dossier_patient.dossiermedical'),
        ),
        migrations.AddField(
            model_name='soin',
            name='dossier_medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='dossier_patient.dossiermedical'),
        ),
        migrations.AddField(
            model_name='soin',
            name='infirmier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='utilisateurs.infirmier'),
        ),
    ]
