# Generated by Django 5.1.4 on 2024-12-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_patient', '0002_patient_remove_dossiermedical_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('infirmier', models.CharField(max_length=100)),
                ('dossier_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='dossier_patient.dossiermedical')),
            ],
        ),
    ]
