# Generated by Django 5.1.4 on 2024-12-23 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_patient', '0005_remove_soin_description_soin_medicaments_administres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medecin',
            field=models.TextField(default='medecin inconnue'),
        ),
        migrations.AddField(
            model_name='patient',
            name='personne',
            field=models.TextField(default='numero inconnue'),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='dossier_patient.patient'),
        ),
    ]
