# Generated by Django 5.1.4 on 2024-12-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_patient', '0006_patient_medecin_patient_personne_and_more'),
        ('utilisateurs', '0009_remove_medicament_duree_remove_medicament_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='utilisateurs.patient'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
