# Generated by Django 5.1.4 on 2024-12-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_patient', '0007_alter_dossiermedical_patient_delete_patient'),
        ('utilisateurs', '0010_alter_ordonnance_dpi_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='infirmier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='utilisateurs.infirmier'),
        ),
    ]
